### ISSUE TITLE
Accessibility checklist

### ISSUE THREAD

**Issue by yonimor** [yonimor/web-app#1]
- [x] Make the tabs, menus, links and other parts keyboard accessible with tabindex and :focus visuals.
- [x] Improve keyboard accessibility with JS (Keypress events to select tabs, open dropdowns etc).
- [x] Make hidden content have aria-hidden="true" and vice versa (JS).
- [x] Make selected tabs have aria-selected="true" and vice versa (JS).
- [x] Add aria-controls="id" attributes to tabs to connect them with tabpanels.
- [x] Also connect tabs and content with aria-owns="id".
- [x] Add required and validations (With and without JS).
- [x] Improve roles and HTML5 accessibility: http://www.w3.org/TR/2008/WD-wai-aria-20080806/#roles
- [x] Add aria-describedby to elements that are described by other elements.
- [x] Add aria-multiselectable="false" to tablist.
- [x] Form accessibility: fieldsets, legends, labels (for="") and inputs.
- [x] Progressive enhancement with JS (Make the best usability possible without JS and then add JS).
- [x] html lang="en".
- [x] Images with alt texts.

**Comment by alexilyaev** [comment]
Great list!

About Progressive Enhancement, when building an SPA (Single Page Application), sometimes you'd like to decide upfront that you support the app only if JS is available.
Meaning, supporting all of the app features without JS and then adding JS would be a huge overkill.
So you could just show a message to people who don't have JS enabled that this app requires JS to work properly.

For this project, this is the case.

**Comment by krulik** [comment]
I would also add some visual representation of focus/active elements. When you tab through the elements you can't see where you're at.
