### ISSUE TITLE
Web-App week 2 checklist

### ISSUE THREAD

**Issue by yonimor** [yonimor/web-app#3]
- [x] If a URL is entered with a hash value, open the right tab on page load.
- [x] Keyboard accessible dropdown menus.
- [x] Rewrite tabs' JS based on the following algorithm (mostly DRY code e.g connecting panels to tabs with a single function): 
- If the entered URL has an hash value - open the correct tab.
- Else open the first tab.
- Attach listeners ('click', 'keypress').
