### ISSUE TITLE
Web-App week 3 checklist

### ISSUE THREAD

**Issue by yonimor** [yonimor/web-app#6]
### Clean Code
- [x] Semantic class / ID names.
- [x] Semantic use of double / single quotes.
- [x] Remove 'e.srcElement' on 'openDropdown' function.
- [x] Make 'isEnterOrSpace' a boolean function.
- [x] Remove 'UTILS.preventEvent' function.
- [x] Limit 'selects' (main.js) with a container scope.
### Clean Design
- [x] Contrast: Change the pink :focus color.
- [x] Custom 'select' arrow.
### Cross Browser Compatibility
- [x] IE8: Full screen background image.
- [x] IE8: Remove calc().
### Events
- [x] Activate anchors with space key.
- [x] Close forms with Esc. key.
### Functionality
- [x] Implement the following layout: http://codepen.io/krulik/pen/dPyqLE?editors=110.
- [x] Layout: Handle dynamic content (AJAX notification).
- [x] Add 'cancel' button to forms.
- [x] Add target="_blank" to arrows.
- [x] Fix 'settings' button.
