### ISSUE TITLE
Web-App week 4 checklist

### ISSUE THREAD

**Issue by yonimor** [yonimor/web-app#8]
### Clean Code
- [x] Function abstraction.
- [x] Comment recent code.
### Functionality
- [x] Enable partial keyword search results.
- [x] Display a notification if a search term is not found.
- [x] Save data in a local storage.
- [ ] Open the last opened report on page reload (not just refresh).
- [ ] Open last report after search.
- [ ] Retest and fix IE8 behavior issues.
- [x] IE8 full screen background image.
